version: "3"

# The acs-deployment project contains the product version of docker-compose.
#
# This version is for testing and development use. For testing and debug we need to have a more open version.
# For remote debug we need the CATALINA_OPTS and to expose port 8000.

# Add the following environment variable to CATALINA_OPTS to activate YourKit profiling agent on tomcat
#-agentpath:/usr/local/YourKit-JavaProfiler-2018.04/bin/linux-x86-64/libyjpagent.so=delay=200000,listen=all,sessionname=$$HOSTNAME,dir=/tmp/Alfresco/yourkit,onexit=snapshot,periodicperf=600,periodicmem=600,probe_off=*

services:
    alfresco:
        image: alfresco/content-repository-azure:latest
        environment:
            CATALINA_OPTS : "
                -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n
                "
            JAVA_OPTS : "
                -Dalfresco.port=8082
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dindex.subsystem.name=noindex
                -Dalfresco.restApi.basicAuthScheme=true
                -Dmessaging.broker.url=\"failover:(tcp://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Dlocal.transform.service.enabled=false
                -Dtransform.service.enabled=false
                -Dcsrf.filter.enabled=false
                -Dconnector.az.account.name=${AZURE_STORAGE_ACCOUNT_NAME}
                -Dconnector.az.account.key=${AZURE_STORAGE_ACCOUNT_KEY}
                -Dconnector.az.containerName=${AZURE_CONTAINER_NAME}
                -Dconnector.az.deleted.containerName=${AZURE_DELETED_CONTAINER_NAME}
                "
        ports:
            - 8082:8080

    postgres:
        image: postgres:11.4
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432

    activemq:
        image: alfresco/alfresco-activemq:5.15.8
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    share:
        image: alfresco/alfresco-share:6.1.0
        depends_on:
            - alfresco
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080
    
    digital-workspace:
        image: alfresco/alfresco-content-app:master
        environment:
            BASE_PATH: ./
        depends_on:
            - alfresco
    
    proxy:
        image: alfresco/alfresco-acs-nginx:3.0.1
        depends_on:
            - alfresco
            - digital-workspace
        environment:
            SYNCSERVICE_URL: http://localhost:8080
        ports:
            - 8080:8080
        links:
            - digital-workspace
            - alfresco
            - share